"""Prompt Caching support for hi-agent.

Injects Anthropic cache_control markers into LLM requests to reduce
input token cost by ~75% on cache hits. The system prompt and first
N messages are stable across turns, making them ideal cache anchors.

Usage:
    from hi_agent.llm.cache import PromptCacheInjector, CacheAwareTokenUsage

    injector = PromptCacheInjector(config=PromptCacheConfig(anchor_messages=3))
    cached_messages = injector.inject(messages)
    cached_system = injector.inject_system(system_prompt)
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import Any, Literal, TypedDict

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


class CacheControlBlock(TypedDict):
    """Anthropic cache_control marker block."""

    type: Literal["ephemeral"]


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class CacheAwareTokenUsage:
    """Token usage extended with Anthropic prompt-caching fields.

    Attributes:
        prompt_tokens: Total input tokens sent to the model.
        completion_tokens: Output tokens generated by the model.
        total_tokens: prompt_tokens + completion_tokens.
        cache_read_tokens: Input tokens served from the cache (~10% price).
        cache_write_tokens: Input tokens written to the cache (~125% price).
    """

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    cache_read_tokens: int = 0
    cache_write_tokens: int = 0

    def effective_cost_multiplier(self) -> float:
        """Return the effective cost ratio relative to a no-cache baseline.

        A value < 1.0 indicates net savings.  The formula weights each token
        bucket by its relative price:
          - Regular input tokens:      1.00x
          - Cache-write tokens:        1.25x  (slightly more expensive)
          - Cache-read tokens:         0.10x  (much cheaper)

        The baseline is all prompt_tokens at 1.00x.
        """
        baseline = max(self.prompt_tokens, 1)
        # Tokens that were neither read from nor written to cache
        regular_tokens = max(
            self.prompt_tokens - self.cache_read_tokens - self.cache_write_tokens, 0
        )
        actual_cost = (
            regular_tokens * 1.00 + self.cache_write_tokens * 1.25 + self.cache_read_tokens * 0.10
        )
        return actual_cost / baseline

    def cache_hit_rate(self) -> float:
        """Return the fraction of prompt tokens served from the cache."""
        return self.cache_read_tokens / max(self.prompt_tokens, 1)


@dataclass
class PromptCacheConfig:
    """Configuration for :class:`PromptCacheInjector`.

    Attributes:
        enabled: Whether to inject cache_control markers at all.
        anchor_messages: Number of leading messages to anchor (system prompt
            is handled separately via :meth:`inject_system`).
        min_cacheable_tokens: Minimum token count below which caching is
            unlikely to be cost-effective (not enforced at injection time;
            callers may use this as a guard).
    """

    enabled: bool = True
    anchor_messages: int = 3
    min_cacheable_tokens: int = 1024


@dataclass
class PromptCacheStats:
    """Cumulative statistics across multiple requests.

    Attributes:
        total_requests: Number of requests processed.
        cache_hits: Number of requests that had at least one cached token.
        total_saved_tokens: Cumulative cache_read_tokens across all requests.
    """

    total_requests: int = 0
    cache_hits: int = 0
    total_saved_tokens: int = 0

    def hit_rate(self) -> float:
        """Return the fraction of requests that had at least one cache hit."""
        return self.cache_hits / max(self.total_requests, 1)

    def update(self, usage: CacheAwareTokenUsage) -> None:
        """Accumulate statistics from a single :class:`CacheAwareTokenUsage`."""
        self.total_requests += 1
        if usage.cache_read_tokens > 0:
            self.cache_hits += 1
            self.total_saved_tokens += usage.cache_read_tokens


# ---------------------------------------------------------------------------
# Injector
# ---------------------------------------------------------------------------


class PromptCacheInjector:
    """Injects Anthropic ``cache_control`` markers into message lists.

    Only the first :attr:`PromptCacheConfig.anchor_messages` non-tool
    messages receive a marker, because those positions are stable across
    turns and are the best candidates for caching.

    Args:
        config: Configuration controlling injection behaviour.
    """

    def __init__(self, config: PromptCacheConfig | None = None) -> None:
        self._config = config or PromptCacheConfig()

    # -- public API -----------------------------------------------------------

    def inject(self, messages: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Return a deep-copied message list with cache_control injected.

        Modifies up to :attr:`PromptCacheConfig.anchor_messages` leading
        messages (skipping ``role="tool"`` messages).  The original list is
        never mutated.

        Args:
            messages: A list of chat message dicts (role / content pairs).

        Returns:
            A new list where eligible messages have cache_control injected
            into the last content block.
        """
        if not self._config.enabled:
            return copy.deepcopy(messages)

        result: list[dict[str, Any]] = copy.deepcopy(messages)
        anchors_remaining = self._config.anchor_messages

        for msg in result:
            if anchors_remaining <= 0:
                break
            if msg.get("role") == "tool":
                # Tool results change every turn — skip them.
                continue
            self._inject_into_message(msg)
            anchors_remaining -= 1

        return result

    def inject_system(self, system_prompt: str) -> list[dict[str, Any]]:
        """Wrap a plain system prompt string in Anthropic's cached array format.

        Anthropic accepts the ``system`` field as either a string or a list of
        content blocks.  Using the list form lets us attach ``cache_control``.

        Args:
            system_prompt: The raw system prompt text.

        Returns:
            A list containing a single text block with ``cache_control``
            set to ``{"type": "ephemeral"}``.
        """
        return [
            {
                "type": "text",
                "text": system_prompt,
                "cache_control": {"type": "ephemeral"},
            }
        ]

    # -- internals ------------------------------------------------------------

    @staticmethod
    def _inject_into_message(msg: dict[str, Any]) -> None:
        """Mutate *msg* in-place to add cache_control to the last content block.

        Handles two content shapes:
        - ``str``: converted to ``[{"type": "text", "text": ..., "cache_control": ...}]``
        - ``list``: the last element gets ``cache_control`` added.
        """
        content = msg.get("content")

        if isinstance(content, str):
            msg["content"] = [
                {
                    "type": "text",
                    "text": content,
                    "cache_control": {"type": "ephemeral"},
                }
            ]
        elif isinstance(content, list) and content:
            last_block = content[-1]
            if isinstance(last_block, dict):
                last_block["cache_control"] = {"type": "ephemeral"}


# ---------------------------------------------------------------------------
# Response parser
# ---------------------------------------------------------------------------


def parse_cache_usage(response_body: dict[str, Any]) -> CacheAwareTokenUsage:
    """Parse an Anthropic API response body into a :class:`CacheAwareTokenUsage`.

    Anthropic returns cache statistics inside the ``usage`` object:
    - ``cache_read_input_tokens``:    tokens served from the prompt cache.
    - ``cache_creation_input_tokens``: tokens written into the prompt cache.

    Args:
        response_body: The raw JSON dict returned by the Anthropic Messages API.

    Returns:
        A :class:`CacheAwareTokenUsage` populated from the response.
    """
    usage: dict[str, Any] = response_body.get("usage", {})

    prompt_tokens: int = usage.get("input_tokens", 0)
    completion_tokens: int = usage.get("output_tokens", 0)
    total_tokens: int = prompt_tokens + completion_tokens
    cache_read_tokens: int = usage.get("cache_read_input_tokens", 0)
    cache_write_tokens: int = usage.get("cache_creation_input_tokens", 0)

    return CacheAwareTokenUsage(
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=total_tokens,
        cache_read_tokens=cache_read_tokens,
        cache_write_tokens=cache_write_tokens,
    )
