"""DelegationManager for hi-agent.

Enables the Runner to spawn isolated child agent runs for parallel
task decomposition. Built on top of agent-kernel's spawn_child_run,
which provides run isolation, lifecycle tracking, and event sourcing.

Design:
- Each DelegationRequest becomes a child run (via kernel.spawn_child_run)
- Child runs are polled until terminal state (completed/failed/aborted)
- Results are summarized via LLM (light tier) before injection into parent context
- Max concurrent children enforced via asyncio.Semaphore
"""

from __future__ import annotations

import asyncio
import logging
import time
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, Literal

if TYPE_CHECKING:
    from hi_agent.llm.protocol import AsyncLLMGateway
    from hi_agent.runtime_adapter.protocol import RuntimeAdapter

from hi_agent.gate_protocol import GatePendingError

logger = logging.getLogger(__name__)

# Terminal states for a child run lifecycle.
_TERMINAL_STATES: frozenset[str] = frozenset({"completed", "failed", "aborted"})


# ---------------------------------------------------------------------------
# Data contracts
# ---------------------------------------------------------------------------


@dataclass
class DelegationRequest:
    """Describes one sub-task to be delegated to a child agent run.

    Attributes:
        goal: Human-readable description of what the child run should accomplish.
        task_id: Unique identifier for this sub-task (generated by the caller).
        role_id: Optional agent role identifier for memory namespace scoping.
            Agents with the same role_id share a memory namespace; different
            role_ids are isolated.  Empty string means no role scoping.
        tool_allowlist: Explicit list of tool names the child run may use.
            ``None`` means the child inherits all tools from the parent.
        budget_fraction: Fraction of the parent's budget allocated to this child.
            Value in (0, 1]; default 0.25.
        max_turns: Maximum number of turns the child run is allowed.
        timeout_seconds: Wall-clock timeout for waiting on the child run.
        config: Arbitrary extra config forwarded to ``spawn_child_run``.
    """

    goal: str
    task_id: str
    role_id: str = ""
    tool_allowlist: list[str] | None = None
    budget_fraction: float = 0.25
    max_turns: int = 20
    timeout_seconds: float = 300.0
    config: dict[str, Any] | None = None


@dataclass
class DelegationResult:
    """Outcome of a single delegated child run.

    Attributes:
        request: The originating ``DelegationRequest``.
        child_run_id: Identifier of the spawned child run in the kernel.
        status: Terminal disposition of the child run.
        summary: LLM-compressed summary of the child run's output, suitable
            for injection into the parent agent's context window.
        raw_output: Raw output from the child run (retained for debugging).
        duration_seconds: Elapsed wall-clock time from spawn to terminal state.
        error: Error message when status is ``"failed"``.
    """

    request: DelegationRequest
    child_run_id: str
    status: Literal["completed", "failed", "aborted", "timeout", "gate_pending"]
    summary: str
    raw_output: str | None = None
    duration_seconds: float = 0.0
    error: str | None = None
    gate_id: str | None = None


@dataclass
class DelegationConfig:
    """Tuning knobs for the DelegationManager.

    Attributes:
        max_concurrent: Maximum number of child runs executing simultaneously.
        poll_interval_seconds: How frequently to poll the kernel for child
            run state changes.
        summary_max_chars: Character budget for each child run summary.
        summary_model_tier: LLM tier used for summarization (``"light"``
            keeps costs low).
    """

    max_concurrent: int = 3
    poll_interval_seconds: float = 2.0
    summary_max_chars: int = 2000
    summary_model_tier: str = "light"


# ---------------------------------------------------------------------------
# ChildRunPoller
# ---------------------------------------------------------------------------


class ChildRunPoller:
    """Polls the kernel until a child run reaches a terminal lifecycle state.

    Args:
        kernel: A ``RuntimeAdapter``-compatible object that exposes
            ``query_run(run_id) -> dict``.
        poll_interval: Seconds to sleep between consecutive polls.
    """

    def __init__(self, kernel: RuntimeAdapter, poll_interval: float = 2.0) -> None:
        self._kernel = kernel
        self._poll_interval = poll_interval

    async def wait_for_completion(
        self,
        child_run_id: str,
        timeout: float,
    ) -> tuple[str, str | None]:
        """Poll until the child run reaches a terminal state or times out.

        Args:
            child_run_id: Identifier of the child run to watch.
            timeout: Maximum seconds to wait before returning ``"timeout"``.

        Returns:
            A ``(status, raw_output)`` tuple where *status* is one of
            ``"completed"``, ``"failed"``, ``"aborted"``, or ``"timeout"``,
            and *raw_output* is the output payload extracted from the run
            snapshot (may be ``None``).
        """
        deadline = time.monotonic() + timeout
        while True:
            try:
                snapshot = self._kernel.query_run(child_run_id)
            except Exception as exc:
                logger.warning("query_run(%s) raised %s — will retry", child_run_id, exc)
                snapshot = {}

            state: str = snapshot.get("lifecycle_state", "")
            if self._is_terminal(state):
                raw_output: str | None = snapshot.get("output") or snapshot.get("result")
                if raw_output is not None and not isinstance(raw_output, str):
                    raw_output = str(raw_output)
                return state, raw_output

            remaining = deadline - time.monotonic()
            if remaining <= 0:
                return "timeout", None

            sleep_for = min(self._poll_interval, remaining)
            await asyncio.sleep(sleep_for)

    @staticmethod
    def _is_terminal(state: str) -> bool:
        """Return ``True`` when *state* represents a run that will not advance."""
        return state in _TERMINAL_STATES


# ---------------------------------------------------------------------------
# ResultSummarizer
# ---------------------------------------------------------------------------


class ResultSummarizer:
    """Compresses child run output to a size suitable for context injection.

    When an :class:`AsyncLLMGateway` is supplied, long outputs are summarised
    using the LLM.  When no gateway is available, the output is simply
    truncated to *max_chars*.

    Args:
        llm: An async LLM gateway, or ``None`` for truncation-only mode.
    """

    def __init__(self, llm: AsyncLLMGateway | None) -> None:
        self._llm = llm

    async def summarize(
        self,
        goal: str,
        raw_output: str,
        max_chars: int,
    ) -> str:
        """Return a summarised (or truncated) version of *raw_output*.

        Short outputs (at or under *max_chars*) are returned verbatim.
        Longer outputs are sent to the LLM for compression when a gateway
        is available; otherwise they are truncated.

        Args:
            goal: The sub-task goal, used as context in the summary prompt.
            raw_output: Full output from the child run.
            max_chars: Maximum character length of the returned string.

        Returns:
            A string of at most *max_chars* characters.
        """
        if not raw_output:
            return ""

        if len(raw_output) <= max_chars:
            return raw_output

        if self._llm is None:
            return raw_output[:max_chars]

        # Build a compressed summary via LLM.
        try:
            from hi_agent.llm.protocol import LLMRequest

            prompt = (
                f"Sub-task goal: {goal}\n"
                f"Sub-task output (pre-summary):\n"
                f"{raw_output[:4000]}\n\n"
                f"Summarize the following output in {max_chars} characters or fewer: "
                f"what was accomplished, key results, issues encountered."
            )
            request = LLMRequest(
                messages=[{"role": "user", "content": prompt}],
                model="default",
                max_tokens=min(max_chars // 2, 1024),
            )
            response = await self._llm.complete(request)
            summary = response.content.strip()
            return summary[:max_chars]
        except Exception as exc:
            logger.warning("LLM summarization failed (%s); falling back to truncation", exc)
            return raw_output[:max_chars]


# ---------------------------------------------------------------------------
# DelegationManager
# ---------------------------------------------------------------------------


class DelegationManager:
    """Orchestrates parallel delegation of sub-tasks to isolated child runs.

    Each :class:`DelegationRequest` is converted into a kernel child run via
    :meth:`RuntimeAdapter.spawn_child_run_async`.  Child runs execute
    concurrently up to *config.max_concurrent*, are polled until they reach
    a terminal state, and their outputs are compressed before being returned
    to the caller.

    Args:
        kernel: Runtime adapter used to spawn and query child runs.
        config: Behavioural parameters for the manager.
        llm: Optional async LLM gateway used to summarize child run outputs.
    """

    def __init__(
        self,
        kernel: RuntimeAdapter,
        config: DelegationConfig,
        llm: AsyncLLMGateway | None = None,
    ) -> None:
        self._kernel = kernel
        self._config = config
        self._llm = llm

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def delegate(
        self,
        requests: list[DelegationRequest],
        parent_run_id: str,
    ) -> list[DelegationResult]:
        """Spawn and await all *requests* as parallel child runs.

        Args:
            requests: Sub-tasks to delegate.
            parent_run_id: The caller's run identifier (used as parent in
                ``spawn_child_run_async``).

        Returns:
            A list of :class:`DelegationResult` objects in the same order
            as *requests*.
        """
        sem = asyncio.Semaphore(self._config.max_concurrent)
        poller = ChildRunPoller(self._kernel, self._config.poll_interval_seconds)
        summarizer = ResultSummarizer(self._llm)

        tasks = [
            self._delegate_one(req, parent_run_id, sem, poller, summarizer) for req in requests
        ]
        raw_results = await asyncio.gather(*tasks, return_exceptions=True)

        results: list[DelegationResult] = []
        for req, outcome in zip(requests, raw_results, strict=True):
            if isinstance(outcome, GatePendingError):
                results.append(
                    DelegationResult(
                        request=req,
                        child_run_id="",
                        status="gate_pending",
                        summary="",
                        gate_id=outcome.gate_id,
                    )
                )
            elif isinstance(outcome, BaseException):
                results.append(
                    DelegationResult(
                        request=req,
                        child_run_id="",
                        status="failed",
                        summary="",
                        error=str(outcome),
                    )
                )
            else:
                results.append(outcome)  # type: ignore[arg-type]  expiry_wave: Wave 27
        return results

    def format_results_for_context(self, results: list[DelegationResult]) -> str:
        """Render *results* as a human-readable block for injection into a TaskView.

        Args:
            results: Completed delegation results.

        Returns:
            A Markdown-style string listing each sub-task's status and summary.
        """
        # Language Rule (CLAUDE.md): prompts to LLMs must be English.
        if not results:
            return "## Sub-task execution results\n\n(no sub-tasks)\n"

        lines: list[str] = ["## Sub-task execution results", ""]
        for idx, result in enumerate(results, start=1):
            lines.append(f"### Sub-task {idx}: {result.request.goal}")
            lines.append(f"Status: {result.status} | Duration: {result.duration_seconds:.1f}s")
            if result.error:
                lines.append(f"Error: {result.error}")
            if result.summary:
                lines.append(result.summary)
            lines.append("")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    async def _delegate_one(
        self,
        req: DelegationRequest,
        parent_run_id: str,
        sem: asyncio.Semaphore,
        poller: ChildRunPoller,
        summarizer: ResultSummarizer,
    ) -> DelegationResult:
        """Execute the full lifecycle for a single delegation request.

        Acquires *sem* before spawning so that no more than
        ``config.max_concurrent`` child runs are active simultaneously.
        """
        async with sem:
            start_time = time.monotonic()
            child_run_id = ""
            try:
                child_config = self._build_config(req)
                child_run_id = await self._kernel.spawn_child_run_async(
                    parent_run_id,
                    req.task_id,
                    config=child_config,
                )
                logger.debug("Spawned child run %s for task_id=%s", child_run_id, req.task_id)

                status, raw_output = await poller.wait_for_completion(
                    child_run_id, req.timeout_seconds
                )

                summary = await summarizer.summarize(
                    req.goal,
                    raw_output or "",
                    self._config.summary_max_chars,
                )

                duration = time.monotonic() - start_time
                return DelegationResult(
                    request=req,
                    child_run_id=child_run_id,
                    status=status,  # type: ignore[arg-type]  expiry_wave: Wave 27
                    summary=summary,
                    raw_output=raw_output,
                    duration_seconds=duration,
                )

            except GatePendingError:
                raise
            except Exception as exc:
                duration = time.monotonic() - start_time
                logger.exception("Delegation failed for task_id=%s: %s", req.task_id, exc)
                return DelegationResult(
                    request=req,
                    child_run_id=child_run_id,
                    status="failed",
                    summary="",
                    duration_seconds=duration,
                    error=str(exc),
                )

    def _build_config(self, req: DelegationRequest) -> dict[str, Any]:
        """Construct the config dict forwarded to ``spawn_child_run_async``.

        Merges *req.config* with delegation-specific fields.

        Args:
            req: The delegation request to derive config from.

        Returns:
            A plain dict suitable as the ``config`` argument of
            ``spawn_child_run_async``.
        """
        merged: dict[str, Any] = dict(req.config or {})
        merged["budget_fraction"] = req.budget_fraction
        merged["max_turns"] = req.max_turns
        if req.tool_allowlist is not None:
            merged["tool_allowlist"] = list(req.tool_allowlist)
        return merged
