"""Default capability handlers for TRACE stage actions."""

from __future__ import annotations

from hi_agent.capability.registry import CapabilityRegistry, CapabilitySpec


def _default_action_handler(payload: dict) -> dict:
    """Handle a stage action with deterministic success/failure behavior.

    Args:
      payload: Action payload generated by runner.

    Returns:
      A normalized action result payload.
    """
    should_fail = bool(payload.get("should_fail", False))
    if should_fail:
        return {"success": False, "score": 0.0, "reason": "forced_failure"}

    return {
        "success": True,
        "score": 1.0,
        "reason": "ok",
        "evidence_hash": f"ev_{payload.get('stage_id', 'unknown')}",
    }


def register_default_capabilities(registry: CapabilityRegistry) -> None:
    """Register baseline capability handlers required by spike/mvp runner.

    Args:
      registry: Capability registry to populate.
    """
    for name in [
        "analyze_goal",
        "search_evidence",
        "build_draft",
        "synthesize",
        "evaluate_acceptance",
    ]:
        registry.register(CapabilitySpec(name=name, handler=_default_action_handler))

