#!/usr/bin/env python3
"""Generate a markdown route inventory table for all hi_agent/server route handlers.

AST-walks routes_*.py and app.py. For each handle_* function, emits:

| handler | tenant_source | object_owner_source | cross_tenant_test |

Where:
    tenant_source:       "ctx.tenant_id" if the handler uses ctx.tenant_id, "MISSING" otherwise
    object_owner_source: "store_param" if tenant_id is passed to a store, "MISSING" otherwise
    cross_tenant_test:   "YES" if a cross-tenant test file exists for the route file, "NO" otherwise

Output: docs/route-inventory.md
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
DOCS_DIR = ROOT / "docs"

# Map route file stem → cross-tenant test file name
CROSS_TENANT_TEST_MAP: dict[str, str] = {
    "routes_runs": "test_cross_tenant_isolation.py",
    "routes_artifacts": "test_routes_artifacts_cross_tenant.py",
    "routes_events": "test_cross_tenant_isolation.py",
    "routes_ops": "test_routes_ops_cross_tenant.py",
    "routes_sessions": "test_routes_sessions_cross_tenant.py",
    "routes_team": "test_routes_team_cross_tenant.py",
    "routes_knowledge": "",
    "routes_manifest": "",
    "routes_memory": "",
    "routes_profiles": "",
    "routes_tools_mcp": "",
    "app": "test_skills_cross_tenant.py",
}

TENANT_SOURCE_INDICATORS = [
    "ctx.tenant_id",
    "require_tenant_context",
]

OWNER_SOURCE_INDICATORS = [
    "tenant_id=ctx.tenant_id",
    "validate_resource_ownership",
    "get_or_404_owned",
    "get_run(run_id, workspace=ctx",
    "list_runs(workspace=ctx",
    "list_active(tenant_id=ctx.tenant_id",
    "validate_ownership(",
    "store.list(",
    "registry.get(",
    "registry.query(",
    "_belongs_to_tenant",
    "handle_tenant != ctx.tenant_id",
    "handle_tenant and handle_tenant != ctx.tenant_id",
    "ctx.tenant_id !=",
    "ctx.tenant_id ==",
]


def _has_tenant_source(func_src: str) -> bool:
    return any(ind in func_src for ind in TENANT_SOURCE_INDICATORS)


def _has_owner_source(func_src: str) -> bool:
    return any(ind in func_src for ind in OWNER_SOURCE_INDICATORS)


def _cross_tenant_test_exists(file_stem: str) -> bool:
    test_name = CROSS_TENANT_TEST_MAP.get(file_stem, "")
    if not test_name:
        return False
    test_path = ROOT / "tests" / "integration" / test_name
    return test_path.exists()


def _scan_file(path: Path) -> list[dict]:
    """Return a list of handler dicts for the given file."""
    src = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return []

    file_stem = path.stem
    has_cross_tenant = _cross_tenant_test_exists(file_stem)

    rows = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            continue
        if not node.name.startswith("handle_"):
            continue
        func_src = ast.get_source_segment(src, node) or ""
        rows.append(
            {
                "handler": node.name,
                "file": str(path.relative_to(ROOT)).replace("\\", "/"),
                "tenant_source": "ctx.tenant_id" if _has_tenant_source(func_src) else "MISSING",
                "object_owner_source": "store_param" if _has_owner_source(func_src) else "MISSING",
                "cross_tenant_test": "YES" if has_cross_tenant else "NO",
            }
        )
    return rows


def main() -> int:
    all_rows: list[dict] = []

    # Scan routes_*.py
    for path in sorted(ROOT.glob("hi_agent/server/routes_*.py")):
        all_rows.extend(_scan_file(path))

    # Scan app.py for inline handlers
    app_path = ROOT / "hi_agent" / "server" / "app.py"
    if app_path.exists():
        all_rows.extend(_scan_file(app_path))

    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = DOCS_DIR / "route-inventory.md"

    lines = [
        "# Route Inventory",
        "",
        "Auto-generated by `scripts/generate_route_inventory.py`. Do not edit manually.",
        "",
        "| handler | file | tenant_source | object_owner_source | cross_tenant_test |",
        "|---------|------|---------------|---------------------|-------------------|",
    ]
    for row in all_rows:
        lines.append(
            f"| {row['handler']} | {row['file']} "
            f"| {row['tenant_source']} | {row['object_owner_source']} "
            f"| {row['cross_tenant_test']} |"
        )

    lines.append("")
    lines.append(f"Total handlers: {len(all_rows)}")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Written: {out_path.relative_to(ROOT)}")
    print(f"Handlers scanned: {len(all_rows)}")

    # Report handlers with MISSING tenant source or object_owner_source
    missing = [r for r in all_rows if r["tenant_source"] == "MISSING"]
    no_owner = [r for r in all_rows if r["object_owner_source"] == "MISSING"]
    if missing:
        print(f"\nHandlers with MISSING tenant_source ({len(missing)}):")
        for r in missing:
            print(f"  {r['file']}::{r['handler']}")
    if no_owner:
        print(f"\nHandlers with MISSING object_owner_source ({len(no_owner)}):")
        for r in no_owner:
            print(f"  {r['file']}::{r['handler']}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
